version: '2'
services:
  db:
    image: 'postgres:13.1-alpine'
    container_name: nagel-database
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
